# Generated by Django 4.1.3 on 2022-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_head", models.CharField(max_length=200)),
                ("news_agency", models.CharField(max_length=100)),
                ("news_date", models.CharField(max_length=200)),
                ("news_img", models.CharField(max_length=200)),
                ("news_link", models.CharField(max_length=200)),
            ],
        ),
    ]
